
import type { Metadata } from "next";
import "../globals.css";
import Header from "@/components/Header/Header";
import { getServerSession } from "next-auth";
import { authOptions } from "@/server/auth";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialSession = await getServerSession(authOptions);

  return (
    <div className="flex flex-col">
        <Header initialSession={initialSession}/>
        {children}
    </div>

  );
}
